#[cfg(feature = "bootstrap")]
pub mod bs_icons;
#[cfg(feature = "font-awesome-brands")]
pub mod fa_brands_icons;
#[cfg(feature = "font-awesome-regular")]
pub mod fa_regular_icons;
#[cfg(feature = "font-awesome-solid")]
pub mod fa_solid_icons;
#[cfg(feature = "feather")]
pub mod fi_icons;
#[cfg(feature = "octicons")]
pub mod go_icons;
#[cfg(feature = "hero-icons-outline")]
pub mod hi_outline_icons;
#[cfg(feature = "hero-icons-solid")]
pub mod hi_solid_icons;
#[cfg(feature = "ionicons")]
pub mod io_icons;
#[cfg(feature = "material-design-icons-action")]
pub mod md_action_icons;
#[cfg(feature = "material-design-icons-alert")]
pub mod md_alert_icons;
#[cfg(feature = "material-design-icons-av")]
pub mod md_av_icons;
#[cfg(feature = "material-design-icons-communication")]
pub mod md_communication_icons;
#[cfg(feature = "material-design-icons-content")]
pub mod md_content_icons;
#[cfg(feature = "material-design-icons-device")]
pub mod md_device_icons;
#[cfg(feature = "material-design-icons-editor")]
pub mod md_editor_icons;
#[cfg(feature = "material-design-icons-file")]
pub mod md_file_icons;
#[cfg(feature = "material-design-icons-hardware")]
pub mod md_hardware_icons;
#[cfg(feature = "material-design-icons-home")]
pub mod md_home_icons;
#[cfg(feature = "material-design-icons-image")]
pub mod md_image_icons;
#[cfg(feature = "material-design-icons-maps")]
pub mod md_maps_icons;
#[cfg(feature = "material-design-icons-navigation")]
pub mod md_navigation_icons;
#[cfg(feature = "material-design-icons-notification")]
pub mod md_notification_icons;
#[cfg(feature = "material-design-icons-places")]
pub mod md_places_icons;
#[cfg(feature = "material-design-icons-social")]
pub mod md_social_icons;
#[cfg(feature = "material-design-icons-toggle")]
pub mod md_toggle_icons;
