#[cfg(feature = "bootstrap")]
pub mod bs_icons;
#[cfg(feature = "font-awesome-brands")]
pub mod fa_brands_icons;
#[cfg(feature = "font-awesome-regular")]
pub mod fa_regular_icons;
#[cfg(feature = "font-awesome-solid")]
pub mod fa_solid_icons;
#[cfg(feature = "feather")]
pub mod fi_icons;
#[cfg(feature = "octicons")]
pub mod go_icons;
#[cfg(feature = "hero-icons-outline")]
pub mod hi_outline_icons;
#[cfg(feature = "hero-icons-solid")]
pub mod hi_solid_icons;
#[cfg(feature = "ionicons")]
pub mod io_icons;
