#[cfg(feature = "bootstrap")]
pub mod bs_icons;
#[cfg(feature = "font-awesome")]
pub mod fa_brands_icons;
#[cfg(feature = "font-awesome")]
pub mod fa_regular_icons;
#[cfg(feature = "font-awesome")]
pub mod fa_solid_icons;
#[cfg(feature = "feather")]
pub mod fi_icons;
#[cfg(feature = "octicons")]
pub mod go_icons;
#[cfg(feature = "hero-icons")]
pub mod hi_outline_icons;
#[cfg(feature = "hero-icons")]
pub mod hi_solid_icons;
#[cfg(feature = "ionicons")]
pub mod io_icons;
